name: lezer
description: Dart port of Lezer - an incremental GLR parser system for CodeMirror.
version: 0.0.1
repository: https://github.com/rlch/codemirror-flutter
homepage: https://github.com/rlch/codemirror-flutter
resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  meta: ^1.11.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.6
