name: codemirror
description: "A native Dart/Flutter port of CodeMirror 6 - a high-performance code editor."
version: 0.0.1
homepage: https://github.com/rlch/codemirror-flutter
repository: https://github.com/rlch/codemirror-flutter
resolution: workspace

environment:
  sdk: ^3.8.1
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0
  characters: ^1.3.0
  follow_the_leader: ^0.5.2
  lezer:
  flutter_markdown: ^0.7.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.26.2

flutter:
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMonoNerdFont-Regular.ttf
        - asset: assets/fonts/JetBrainsMonoNerdFont-Italic.ttf
          style: italic
        - asset: assets/fonts/JetBrainsMonoNerdFont-Bold.ttf
          weight: 700
        - asset: assets/fonts/JetBrainsMonoNerdFont-BoldItalic.ttf
          weight: 700
          style: italic
